GHA: take 6 [ci skip]

diff --git a/.github/workflows/test-coverage.yaml b/.github/workflows/test-coverage.yaml
--- a/.github/workflows/test-coverage.yaml
+++ b/.github/workflows/test-coverage.yaml
@@ -13,6 +13,13 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
+      - name: Assert CODECOV_TOKEN is set
+        run: |
+          if [[ -n "${{secrets.CODECOV_TOKEN}}" ]]; then
+            >&2 echo "ERROR: 'secrets.CODECOV_TOKEN' not set"
+            exit 1
+          fi
+
       - uses: r-lib/actions/setup-r@v2
         with:
           use-public-rspm: true
@@ -24,7 +31,6 @@ jobs:
 
       - name: Test coverage
         run: |
-          str(list(token="${{secrets.CODECOV_TOKEN}}"))
           cov <- covr::package_coverage(
             quiet = FALSE,
             clean = FALSE,
